### ISSUE TITLE
MR the initial work order summary.....

### ISSUE THREAD

**Issue by mmiklos-lab** [mmiklos-lab/MR#28]
BMC Requested Assignee: Bob Test

can you please assign BOB

The Actual Assignee From GitHub Is: FFCMERINO AND MMIKLOS

**Comment by ffcmerino** [comment]
Thank you for sending this - we will look into it....

**Comment by ffcmerino** [comment]
stars

**Comment by ffcmerino** [comment]
more stars

**Comment by mmiklos-lab** [comment]
(Comment from Presales Team):

even more stars

**Comment by mmiklos-lab** [comment]
(Comment from tasktop):

(Comment from Deric Merino):

more stars

and even more
